ERROR 24-04-12 09:46:25[reactor-http-nio-2] [WebClientApp:144] - Error making API request: Connection prematurely closed BEFORE response
ERROR 24-04-12 09:46:25[boundedElastic-1] [ControllerUCRM:266] - Error Messge : argument "content" is null
ERROR 24-04-12 10:05:19[reactor-http-nio-3] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-4] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-5] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-6] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-7] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-8] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-1] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-2] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-3] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-4] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-5] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-6] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-7] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:19[reactor-http-nio-8] [MessageToApim:35] - Error making API request: Connection refused: no further information: localhost/127.0.0.1:8084
ERROR 24-04-12 10:05:46[http-nio-8083-exec-2] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 10:05:47[http-nio-8083-exec-2] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 10:30:24[test-task-scheduling1] [WebClientApp:89] - Error occurred during access token refresh: error
com.mypurecloud.sdk.v2.ApiException: error
	at com.mypurecloud.sdk.v2.ApiClient.interpretConnectorResponse(ApiClient.java:763)
	at com.mypurecloud.sdk.v2.ApiClient.getAPIResponse(ApiClient.java:815)
	at com.mypurecloud.sdk.v2.ApiClient.authorizeClientCredentials(ApiClient.java:307)
	at gc.apiClient.webclient.WebClientApp.getAccessToken(WebClientApp.java:82)
	at gc.apiClient.controller.ControllerUCRM.RefreshToken(ControllerUCRM.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
ERROR 24-04-12 10:31:08[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:09[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:09[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:09[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:10[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:10[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:11[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:11[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:12[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:12[http-nio-8083-exec-2] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 10:31:12[http-nio-8083-exec-2] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:31:13[http-nio-8083-exec-2] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 10:38:35[test-task-scheduling2] [WebClientApp:89] - Error occurred during access token refresh: error
com.mypurecloud.sdk.v2.ApiException: error
	at com.mypurecloud.sdk.v2.ApiClient.interpretConnectorResponse(ApiClient.java:763)
	at com.mypurecloud.sdk.v2.ApiClient.getAPIResponse(ApiClient.java:815)
	at com.mypurecloud.sdk.v2.ApiClient.authorizeClientCredentials(ApiClient.java:307)
	at gc.apiClient.webclient.WebClientApp.getAccessToken(WebClientApp.java:82)
	at gc.apiClient.controller.ControllerUCRM.RefreshToken(ControllerUCRM.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
ERROR 24-04-12 10:38:47[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:47[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:48[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:48[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:48[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:49[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:49[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:38:50[http-nio-8083-exec-1] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:42:59[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:42:59[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:42:59[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:43:00[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:43:00[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:43:01[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:43:01[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:43:02[http-nio-8083-exec-5] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:31[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:31[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:31[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:31[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:32[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:32[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:33[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:34[http-nio-8083-exec-8] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 10:47:34[reactor-http-nio-4] [WebClientApp:144] - Error making API request: 404 Not Found from GET https://api.apne2.pure.cloud/api/v2/outbound/campaigns/89fe5559-e986-47a7-a7a9-f043777b12bf
ERROR 24-04-12 10:47:34[http-nio-8083-exec-8] [ControllerUCRM:563] - Error Message : Index 1 out of bounds for length 1
ERROR 24-04-12 11:01:42[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:42[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:42[http-nio-8083-exec-10] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 11:01:42[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:43[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:43[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:44[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:44[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:45[http-nio-8083-exec-10] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:01:46[http-nio-8083-exec-10] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 11:01:46[http-nio-8083-exec-10] [ControllerUCRM:554] - Error Message
ERROR 24-04-12 11:30:38[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:39[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:39[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:39[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:40[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:40[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:41[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:42[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:42[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 11:30:43[http-nio-8083-exec-3] [ControllerUCRM:545] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:49[test-task-scheduling1] [WebClientApp:89] - Error occurred during access token refresh: error
com.mypurecloud.sdk.v2.ApiException: error
	at com.mypurecloud.sdk.v2.ApiClient.interpretConnectorResponse(ApiClient.java:763)
	at com.mypurecloud.sdk.v2.ApiClient.getAPIResponse(ApiClient.java:815)
	at com.mypurecloud.sdk.v2.ApiClient.authorizeClientCredentials(ApiClient.java:307)
	at gc.apiClient.webclient.WebClientApp.getAccessToken(WebClientApp.java:82)
	at gc.apiClient.controller.ControllerUCRM.RefreshToken(ControllerUCRM.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:01:59[http-nio-8083-exec-2] [ControllerUCRM:548] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:43[test-task-scheduling1] [WebClientApp:89] - Error occurred during access token refresh: error
com.mypurecloud.sdk.v2.ApiException: error
	at com.mypurecloud.sdk.v2.ApiClient.interpretConnectorResponse(ApiClient.java:763)
	at com.mypurecloud.sdk.v2.ApiClient.getAPIResponse(ApiClient.java:815)
	at com.mypurecloud.sdk.v2.ApiClient.authorizeClientCredentials(ApiClient.java:307)
	at gc.apiClient.webclient.WebClientApp.getAccessToken(WebClientApp.java:82)
	at gc.apiClient.controller.ControllerUCRM.RefreshToken(ControllerUCRM.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:52[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:53[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:11:53[http-nio-8083-exec-2] [ControllerUCRM:549] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:13[test-task-scheduling2] [WebClientApp:89] - Error occurred during access token refresh: error
com.mypurecloud.sdk.v2.ApiException: error
	at com.mypurecloud.sdk.v2.ApiClient.interpretConnectorResponse(ApiClient.java:763)
	at com.mypurecloud.sdk.v2.ApiClient.getAPIResponse(ApiClient.java:815)
	at com.mypurecloud.sdk.v2.ApiClient.authorizeClientCredentials(ApiClient.java:307)
	at gc.apiClient.webclient.WebClientApp.getAccessToken(WebClientApp.java:82)
	at gc.apiClient.controller.ControllerUCRM.RefreshToken(ControllerUCRM.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
ERROR 24-04-12 13:17:32[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:32[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:32[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:32[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:33[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:33[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:33[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:33[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:33[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 13:17:33[http-nio-8083-exec-1] [ControllerUCRM:550] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 14:31:58[main] [SpringApplication:851] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'controllerUCRM' defined in file [D:\GitWorkSpace\gcClient\gcClient\target\classes\gc\apiClient\controller\ControllerUCRM.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'servicePostgre' defined in file [D:\GitWorkSpace\gcClient\gcClient\target\classes\gc\apiClient\service\ServicePostgre.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'repository_Ucrm' defined in gc.apiClient.repository.postgresql.Repository_Ucrm defined in @EnableJpaRepositories declared on PostgresqlDataSourceConfig: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Reason: Failed to create query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Cannot compare left expression of type 'gc.apiClient.embeddable.Ucrm' with right expression of type 'java.lang.String'
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at gc.apiClient.GcClientApplication.main(GcClientApplication.java:17)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servicePostgre' defined in file [D:\GitWorkSpace\gcClient\gcClient\target\classes\gc\apiClient\service\ServicePostgre.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'repository_Ucrm' defined in gc.apiClient.repository.postgresql.Repository_Ucrm defined in @EnableJpaRepositories declared on PostgresqlDataSourceConfig: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Reason: Failed to create query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Cannot compare left expression of type 'gc.apiClient.embeddable.Ucrm' with right expression of type 'java.lang.String'
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785)
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repository_Ucrm' defined in gc.apiClient.repository.postgresql.Repository_Ucrm defined in @EnableJpaRepositories declared on PostgresqlDataSourceConfig: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Reason: Failed to create query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Cannot compare left expression of type 'gc.apiClient.embeddable.Ucrm' with right expression of type 'java.lang.String'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785)
	... 33 common frames omitted
Caused by: org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Reason: Failed to create query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Cannot compare left expression of type 'gc.apiClient.embeddable.Ucrm' with right expression of type 'java.lang.String'
	at org.springframework.data.repository.query.QueryCreationException.create(QueryCreationException.java:101)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:115)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.mapMethodsToQuery(QueryExecutorMethodInterceptor.java:99)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:88)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:88)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:357)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:135)
	at org.springframework.data.util.Lazy.get(Lazy.java:113)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:132)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1820)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1769)
	... 44 common frames omitted
Caused by: java.lang.IllegalArgumentException: Failed to create query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteById(java.lang.String); Cannot compare left expression of type 'gc.apiClient.embeddable.Ucrm' with right expression of type 'java.lang.String'
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:106)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:124)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:258)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:95)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:111)
	... 56 common frames omitted
Caused by: org.hibernate.query.SemanticException: Cannot compare left expression of type 'gc.apiClient.embeddable.Ucrm' with right expression of type 'java.lang.String'
	at org.hibernate.query.sqm.internal.TypecheckUtil.assertComparable(TypecheckUtil.java:358)
	at org.hibernate.query.sqm.tree.predicate.SqmComparisonPredicate.<init>(SqmComparisonPredicate.java:48)
	at org.hibernate.query.sqm.tree.predicate.SqmComparisonPredicate.<init>(SqmComparisonPredicate.java:34)
	at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.equal(SqmCriteriaNodeBuilder.java:2121)
	at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.equal(SqmCriteriaNodeBuilder.java:192)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator$PredicateBuilder.build(JpaQueryCreator.java:312)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.toPredicate(JpaQueryCreator.java:210)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.create(JpaQueryCreator.java:121)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.create(JpaQueryCreator.java:1)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createCriteria(AbstractQueryCreator.java:119)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:218)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$CountQueryPreparer.<init>(PartTreeJpaQuery.java:361)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:102)
	... 60 common frames omitted
ERROR 24-04-12 14:40:01[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 14:40:01[http-nio-8083-exec-2] [ControllerUCRM:580] - Error Message : Expecting a SELECT query : `DELETE FROM Entity_Ucrm c WHERE c.topcDataIsueSno = :issueNo`
ERROR 24-04-12 14:50:45[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 14:50:45[http-nio-8083-exec-2] [ControllerUCRM:580] - Error Message : Expecting a SELECT query : `DELETE FROM Entity_Ucrm c WHERE c.topcDataIsueSno = :issueNo`
ERROR 24-04-12 14:55:26[main] [SpringApplication:851] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'controllerUCRM' defined in file [D:\GitWorkSpace\gcClient\gcClient\target\classes\gc\apiClient\controller\ControllerUCRM.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'servicePostgre' defined in file [D:\GitWorkSpace\gcClient\gcClient\target\classes\gc\apiClient\service\ServicePostgre.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'repository_Ucrm' defined in gc.apiClient.repository.postgresql.Repository_Ucrm defined in @EnableJpaRepositories declared on PostgresqlDataSourceConfig: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String); Reason: Validation failed for query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at gc.apiClient.GcClientApplication.main(GcClientApplication.java:17)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'servicePostgre' defined in file [D:\GitWorkSpace\gcClient\gcClient\target\classes\gc\apiClient\service\ServicePostgre.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'repository_Ucrm' defined in gc.apiClient.repository.postgresql.Repository_Ucrm defined in @EnableJpaRepositories declared on PostgresqlDataSourceConfig: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String); Reason: Validation failed for query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1191)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785)
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repository_Ucrm' defined in gc.apiClient.repository.postgresql.Repository_Ucrm defined in @EnableJpaRepositories declared on PostgresqlDataSourceConfig: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String); Reason: Validation failed for query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:907)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:785)
	... 33 common frames omitted
Caused by: org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String); Reason: Validation failed for query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String)
	at org.springframework.data.repository.query.QueryCreationException.create(QueryCreationException.java:101)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:115)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.mapMethodsToQuery(QueryExecutorMethodInterceptor.java:99)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:88)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:88)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:357)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:135)
	at org.springframework.data.util.Lazy.get(Lazy.java:113)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:132)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1820)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1769)
	... 44 common frames omitted
Caused by: java.lang.IllegalArgumentException: Validation failed for query for method public abstract void gc.apiClient.repository.postgresql.Repository_Ucrm.deleteByTopcDataIsueSno(java.lang.String)
	at org.springframework.data.jpa.repository.query.SimpleJpaQuery.validateQuery(SimpleJpaQuery.java:100)
	at org.springframework.data.jpa.repository.query.SimpleJpaQuery.<init>(SimpleJpaQuery.java:70)
	at org.springframework.data.jpa.repository.query.JpaQueryFactory.fromMethodWithQueryString(JpaQueryFactory.java:60)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$DeclaredQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:170)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:252)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:95)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:111)
	... 56 common frames omitted
Caused by: java.lang.IllegalArgumentException: org.hibernate.query.sqm.UnknownPathException: Could not resolve attribute 'topcDataIsueSno' of 'gc.apiClient.embeddable.Ucrm' [DELETE FROM Entity_Ucrm c WHERE c.id.topcDataIsueSno = :issueNo]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:143)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:827)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:732)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:133)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:364)
	at jdk.proxy2/jdk.proxy2.$Proxy120.createQuery(Unknown Source)
	at org.springframework.data.jpa.repository.query.SimpleJpaQuery.validateQuery(SimpleJpaQuery.java:94)
	... 62 common frames omitted
Caused by: org.hibernate.query.sqm.UnknownPathException: Could not resolve attribute 'topcDataIsueSno' of 'gc.apiClient.embeddable.Ucrm' [DELETE FROM Entity_Ucrm c WHERE c.id.topcDataIsueSno = :issueNo]
	at org.hibernate.query.hql.internal.StandardHqlTranslator.translate(StandardHqlTranslator.java:87)
	at org.hibernate.query.internal.QueryInterpretationCacheStandardImpl.createHqlInterpretation(QueryInterpretationCacheStandardImpl.java:165)
	at org.hibernate.query.internal.QueryInterpretationCacheStandardImpl.resolveHqlInterpretation(QueryInterpretationCacheStandardImpl.java:147)
	at org.hibernate.internal.AbstractSharedSessionContract.interpretHql(AbstractSharedSessionContract.java:769)
	at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:819)
	... 69 common frames omitted
Caused by: org.hibernate.query.sqm.PathElementException: Could not resolve attribute 'topcDataIsueSno' of 'gc.apiClient.embeddable.Ucrm'
	at org.hibernate.query.sqm.SqmPathSource.getSubPathSource(SqmPathSource.java:95)
	at org.hibernate.query.sqm.tree.domain.AbstractSqmPath.get(AbstractSqmPath.java:203)
	at org.hibernate.query.sqm.tree.domain.SqmEmbeddedValuedSimplePath.resolvePathPart(SqmEmbeddedValuedSimplePath.java:89)
	at org.hibernate.query.hql.internal.DomainPathPart.resolvePathPart(DomainPathPart.java:42)
	at org.hibernate.query.hql.internal.BasicDotIdentifierConsumer.consumeIdentifier(BasicDotIdentifierConsumer.java:91)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSimplePath(SemanticQueryBuilder.java:5050)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitIndexedPathAccessFragment(SemanticQueryBuilder.java:4999)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitGeneralPathFragment(SemanticQueryBuilder.java:4974)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitGeneralPathExpression(SemanticQueryBuilder.java:1776)
	at org.hibernate.grammars.hql.HqlParser$GeneralPathExpressionContext.accept(HqlParser.java:7699)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at org.hibernate.grammars.hql.HqlParserBaseVisitor.visitBarePrimaryExpression(HqlParserBaseVisitor.java:756)
	at org.hibernate.grammars.hql.HqlParser$BarePrimaryExpressionContext.accept(HqlParser.java:7157)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.createComparisonPredicate(SemanticQueryBuilder.java:2429)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitComparisonPredicate(SemanticQueryBuilder.java:2392)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitComparisonPredicate(SemanticQueryBuilder.java:269)
	at org.hibernate.grammars.hql.HqlParser$ComparisonPredicateContext.accept(HqlParser.java:6164)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitWhereClause(SemanticQueryBuilder.java:2244)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitDeleteStatement(SemanticQueryBuilder.java:636)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitStatement(SemanticQueryBuilder.java:413)
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.buildSemanticModel(SemanticQueryBuilder.java:311)
	at org.hibernate.query.hql.internal.StandardHqlTranslator.translate(StandardHqlTranslator.java:71)
	... 73 common frames omitted
ERROR 24-04-12 14:58:45[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 14:58:45[http-nio-8083-exec-2] [ControllerUCRM:580] - Error Message : Expecting a SELECT query : `DELETE FROM Entity_Ucrm c WHERE c.topcDataIsueSno = :issueNo`
ERROR 24-04-12 15:02:15[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:15[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:15[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:02:16[http-nio-8083-exec-2] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:30[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:30[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:30[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:30[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:30[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:31[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:31[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:31[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:31[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:11:31[http-nio-8083-exec-5] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:20[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:20[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:20[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:20[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:20[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:21[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:21[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:21[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:21[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:19:21[http-nio-8083-exec-3] [ControllerUCRM:554] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:40:44[http-nio-8083-exec-2] [ControllerUCRM:486] - Error Message : JSONObject["payload"] not found.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:52[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:53[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
ERROR 24-04-12 15:43:53[boundedElastic-2] [ControllerUCRM:560] - DataIntegrityViolationException 발생 : Record with the given composite key already exists.
